version: "3"
services:
  restaurantes:
    build: ./restaurantes-rest
    ports:
      - 8080:8080
    networks:
      - arso
    environment:
      OPINIONES_API_URL: http://opiniones:5000/api/
      RESTAURANTE_API_URL: http://localhost:8080/api/
      MONGODB_URL: mongodb://arso:arso@ac-fpzdwce-shard-00-00.akucgja.mongodb.net:27017,ac-fpzdwce-shard-00-01.akucgja.mongodb.net:27017,ac-fpzdwce-shard-00-02.akucgja.mongodb.net:27017/?ssl=true&replicaSet=atlas-fdh11t-shard-0&authSource=admin&retryWrites=true&w=majority
      _URL_AMQP: amqps://hygkafmz:bg8J4YyAUyaY-m2GFtYEcuNhX49cAjpW@rattlesnake.rmq.cloudamqp.com/hygkafmz
      PASARELA_SECRET: 01u3J81mMk

  opiniones:
    build: ./opiniones-rest
    ports:
      - 5000:5000
    networks:
      - arso
    environment:
      OPINIONES_API_URL: http://opiniones:5000/api/
      RESTAURANTE_API_URL: http://restaurantes:8080/api/
      MONGODB_URL: mongodb://arso:arso@ac-fpzdwce-shard-00-00.akucgja.mongodb.net:27017,ac-fpzdwce-shard-00-01.akucgja.mongodb.net:27017,ac-fpzdwce-shard-00-02.akucgja.mongodb.net:27017/?ssl=true&replicaSet=atlas-fdh11t-shard-0&authSource=admin&retryWrites=true&w=majority
      _URL_AMQP: amqps://hygkafmz:bg8J4YyAUyaY-m2GFtYEcuNhX49cAjpW@rattlesnake.rmq.cloudamqp.com/hygkafmz
      PASARELA_SECRET: 01u3J81mMk

  pasarela:
    build: ./pasarela
    ports:
      - 8090:8090
    networks:
      - arso
    environment:
      OPINIONES_API_URL: http://opiniones:5000/api/
      RESTAURANTE_API_URL: http://restaurantes:8080/api/
      MONGODB_URL: mongodb://arso:arso@ac-fpzdwce-shard-00-00.akucgja.mongodb.net:27017,ac-fpzdwce-shard-00-01.akucgja.mongodb.net:27017,ac-fpzdwce-shard-00-02.akucgja.mongodb.net:27017/?ssl=true&replicaSet=atlas-fdh11t-shard-0&authSource=admin&retryWrites=true&w=majority
      _URL_AMQP: amqps://hygkafmz:bg8J4YyAUyaY-m2GFtYEcuNhX49cAjpW@rattlesnake.rmq.cloudamqp.com/hygkafmz
      PASARELA_SECRET: 01u3J81mMk

networks:
  arso:
